### ISSUE TITLE
"No devices found" when trying to read/program/erase.

### ISSUE THREAD

**Issue by siltemc** [islandcontroller/fiberaudio-108#1]
Hi,

I am having trouble using your tool to program the EEPROM of a CM108B in windows.
I can not seem to find my USB audio device when using your script. 
Example:
`python .\cm108ah.py erase`
`Entering ERASE mode.`
`No devices found.`

What can I do to resolve this?

I have confirmed operation of the device with a speaker and microphone in windows. As well as buttons/GPIO with an USB HID sniffer.

My understanding of the CM108B IC is that it is almost entirely the same as the CM108AH but with improved USB codec and internal crystal so your script should be able to talk to the EEPROM.

**Comment by islandcontroller** [comment]
Hi there!

Thanks for the info on the codec and the crystal - I remember the differences were not too clear when designing the board.

Regarding the error message - I vaguely remember the `-B` variant using a different USB product ID than the `-AH`. I only have `-AH` chips on hand so I can't verify this myself unfortunately. If you know the correct one, the device filter can be modified in [`cm108ah.py#L27-L28`](https://github.com/islandcontroller/fiberaudio-108/blob/992eb214d844c5d7319f5c335846821c9f03a4d2/sw/cm108ah.py#L27-L28)!

I'll put it on the ToDo to implement a `vid:pid` input and add the `-B` PID to the filter.

Let me know if this worked! :)
