### ISSUE TITLE
Possibility to work with CM108B

### ISSUE THREAD

**Issue by monotech** [islandcontroller/fiberaudio-108#2]
Hello. I am prototyping a project using CM108B, which is the chip currently available at electronics distributors.
It seems similar to its predecessors. The datasheet is almost the same, including the EEPROM section.

I can successfully read the EEPROM using your utility, but not write.

Also, I am probably missing something, but setting a product name longer than 16 characters is not allowed, but the datasheet says 30 characters, and I have CM108 device with a >16-character EEPROM-configured product name here.

Thanks!

**Comment by islandcontroller** [comment]
Hi, thanks for raising this issue!

Regarding the 16 character limit - this indeed seems to be an error in the configuration processor, as the string descriptor contents are converted from ASCII to UTF-16LE by the CM108, internally. The correct limit is 31 characters for the manufacturer and product names (the "extra" character is stored in the same EEPROM word as the string length field).

Regarding write access to the EEPROM - it should be possible to write to the EEPROM using both -AH and -B parts. I did notice the tool now fails read-back when using the the driver version I re-published. As the memory contents get verified after programming anyway, I believe it is safe to remove the read-back verification/re-try part of the write operation.

I should be able to push fixes for both shortly.
Best regards!

**Comment by monotech** [comment]
Awesome! That works fine, and I can now program the EEPROM on a CM108 and CM108B device.

Something else:
If I try to change the USB IDs, even after setting `enable_usb_ids: bool = True` on line 1139, I will get this warning and the USB IDs will be replaced with defaults:
`warnings.warn('Setting of USB IDs disabled - overriding with default (Cmedia CM108AH VID/PID)')`

EDIT: NEVERMIND, I got it working by making the change on line 1148 instead, changing to: `self._enable_usb_ids = True`
I suspect this may also be the wrong way to do it. I don't know how to Python.

**Comment by islandcontroller** [comment]
Awesome, thanks for the feedback! :)

If you're using the command line tool for programming, use the `--enable-usb-ids 1` option to enable writing those bytes! The value you mentioned provides a default value for the `ConfgiurationReader` constructor, which in this case will get overridden by commandline arguments.

Note however, once you change the IDs, the tool won't detect the CM108 by default anymore. In that case, just add your custom IDs as commandline options with `--vid 0x.... --pid 0x....`.

semi-edit: ahh, ok! You got it to work before I could hit 'send' :D No worries!
